#!/usr/bin/perl

use strict;
use warnings;

use lib './lib';
use MogileFS::Utils;

my $util = MogileFS::Utils->new;
my $usage = "--trackers=host --domain=foo --key='/hello.jpg' --file='./hello.jpg'";
my $c = $util->getopts($usage, qw/class=s key=s file=s/);

my $mogc = $util->client;

my $filename = $c->{file};

my $fh;
my $size = 0;
if ($filename eq '-') {
    $fh = *STDIN;
} else {
    $size = -s $filename;
    die "Could not stat " . $filename unless defined $size;
    open($fh, "< $filename") or die "Could not open " . $filename;
}

my $mf = $mogc->new_file($c->{key}, $c->{class}, undef);
if ($mogc->errcode) {
    die "Error opening MogileFS file: " . $mogc->errstr;
}

my $buf;
while (my $read = read($fh, $buf, 1024 * 1024)) {
    die "error reading file" unless defined $read;
    $mf->print($buf);
}

unless ($mf->close) {
    die "Error writing file: " . $mogc->errcode . ": " . $mogc->errstr;
}
